name: tennis_analytics
channels:
  - defaults
dependencies:
  - python=3.11.5
  - pip
  - pip:  
    - scrapy==2.15.2
    - pandas==3.0.3
    - beautifulsoup4==4.12.3
    - lxml==6.1.0
    - itemloaders==1.4.0
    - parsel==1.11.0
    - w3lib==2.3.1
    - matplotlib==3.9.2
    - seaborn==0.13.2
    - ipykernel==6.29.5
